#!/usr/bin/env python
import dapper
import sys

def help():
    print '''\
Usage: dapper <command> [<arg> ...]

Commands:
  help             Shows this help message.
  compile          Compiles code in a project.
  call             Calls a function in a compiled contract.
  send             Sends a transaction interacting with a contract.
  run-tests        Runs tests for the project using a simulated network.
  get-sigs         Outputs addresses and signatures for contracts.
  new-dapp         Sets up a new dapp directory.
  raw-rpc          CLI for using JSON RPC with your local ethereum node.

Use 'dapper <command> help' to see more detailed help for each command.
'''
################################################################################
#        1         2         3         4         5         6         7         8

def compile(contract):
    pass

def call(contract, function, *args):
    pass

def send(contract, function, *args):
    pass

def run_tests():
    pass

def get_sigs():
    pass

def new_dapp():
    pass

def raw_rpc(method, *args):
    pass

def main():
    commands = {
        "help", "compile", "call",
        "send", "run-tests", "get-sigs", "new-dapp"}
    if sys.argv[1] not in commands:
        print "Invalid command."
        help()
        sys.exit(1)
    else:
        globals()[sys.argv[1].replace('-', '_')](*sys.argv[2:])
        sys.exit(0)
