#!/usr/bin/env python
import dapper
import sys

################################################################################
#        1         2         3         4         5         6         7         8

def main():
    commands = {
        "help", "compile", "call",
        "send", "run-tests", "get-sigs", "new-dapp"}

    if len(sys.argv) > 1:
        command = sys.argv[1]
    else:
        command = 'help'

    if command not in commands:
        print "Invalid command."
        dapper.help.main()
        sys.exit(1)
    else:
        command = command.replace('-', '_')
        submodule = getattr(dapper, command)
        submodule.main(*sys.argv[2:])
        sys.exit(0)

if __name__ == '__main__':
    main()
